INSERT INTO [dbo].[catedratico] ([Id], [nombre_cat], [estado]) VALUES (N'01', N'Luis Fernandez', N'activo')
INSERT INTO [dbo].[catedratico] ([Id], [nombre_cat], [estado]) VALUES (N'02', N'Alejandro Perez', N'inactivo')
INSERT INTO [dbo].[catedratico] ([Id], [nombre_cat], [estado]) VALUES (N'03', N'pedro Morales', N'activo')
INSERT INTO [dbo].[catedratico] ([Id], [nombre_cat], [estado]) VALUES (N'04', N'Mario Lopez', N'activo')
INSERT INTO [dbo].[catedratico] ([Id], [nombre_cat], [estado]) VALUES (N'05', N'Andres Perez', N'activo')
